### ISSUE TITLE
Crash with 2.0.0 

### ISSUE THREAD

**Issue by Airisii** [DragonMountsTeam/DragonMounts2-Continued#36]
Adding the 2.0.0 version of dragon mounts 2 causes crashing on world load. 
[crash-2024-12-06_18.28.47-server.txt](https://github.com/user-attachments/files/18044980/crash-2024-12-06_18.28.47-server.txt)

**Comment by 2190303755** [comment]
How can you tell that it's because of our mod that crashed when you've installed a bunch of other mos yourself?😅

**Comment by 2190303755** [comment]
You can test [the latest snapshot](https://github.com/DragonMountsTeam/DragonMounts2-Continued/releases/tag/24w49a).
