### ISSUE TITLE
Mini dragon Hitbox

### ISSUE THREAD

**Issue by al-wei** [DragonMountsTeam/DragonMounts2-Continued#38]
![2024-12-07_15 07 45](https://github.com/user-attachments/assets/88d06c7c-b04a-4407-a5ba-ff42181cda41)
Hitbox ADAPTS to the size of a mini dragon.

**Comment by 2190303755** [comment]
I can't understand what you are saying

**Comment by 2190303755** [comment]
detailed description is more effective than countless screenshots

**Comment by al-wei** [comment]
The Mini dragon's Hitbox is too big.
迷你龙的Hitbox 太大了。
Can you make the Hitbox the size of a mini dragon?
可不可以吧Hitbox 变成迷你龙的大小。

**Comment by 2190303755** [comment]
让我们说中文

**Comment by 2190303755** [comment]
但是这个模组没有迷你龙吧（

**Comment by al-wei** [comment]
森林龙蛋附近的小龙看见了吗，我发图了。小龙应该是装饰没什么用，但是碰撞箱太大了，阻挡性有些强，有时候点附近箱子都点不到。

**Comment by 2190303755** [comment]
奇怪，你的龙是怎么生成的
我这边的龙在幼年时期的判定箱貌似是正常的

**Comment by al-wei** [comment]
我说的是深林龙蛋，自然生成哪个建筑结构。不是孵化的末影龙。我可是附图了的。

![image](https://github.com/user-attachments/assets/28e166ee-ea4d-40b0-92a5-10dc742f603d)

**Comment by 2190303755** [comment]
到底是龙蛋碰撞箱有问题还是“迷你龙”的碰撞箱有问题

**Comment by al-wei** [comment]
我猜，最初的开发者，直接用的末影龙的模型碰撞箱吧。

**Comment by al-wei** [comment]
不是说了，迷你龙吗？自然生成的结构中有龙蛋，龙蛋附近有一条小龙。

**Comment by al-wei** [comment]
自己放的龙蛋不会有的，自然生成的就有。

**Comment by 2190303755** [comment]
![image](https://github.com/user-attachments/assets/dcc27d35-217e-49cc-a009-0e7c476133fb)
![image](https://github.com/user-attachments/assets/a6023396-b3ef-47c5-af33-26fc2e173049)
但是森林龙巢生成不带实体吧

**Comment by al-wei** [comment]
啊，那就是其它模组。影响了龙蛋。
